# Site Specific Configuration
name: Wès
description: Wès writes
url: https://wès.me
author: wès
timezone: Europe/Rome
timezone_short: CET

license:
  link: 'https://creativecommons.org/licenses/by-nc/4.0'
  label: 'CC BY-NC 4.0'
author:
  name: Valerio Pizzichini
  email: valerio.pizzichini@pm.me

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed


# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jemoji

