# Site Specific Configuration
name: Wes Writes
title: Wes Writes di Valerio Pizzichini 
description: Wès writes di Valerio Pizzichini
url: https://weswrites.me/
timezone: Europe/Rome
timezone_short: CET

keywords: [
  'sf3ris',
  'wès',
  'writes',
  'weswrites',
  'valerio',
  'pizzichini',
  'neovim',
  'nvim',
  'tech blog',
]

license:
  link: 'https://creativecommons.org/licenses/by-nc/4.0'
  label: 'CC BY-NC 4.0'
author:
  name: Valerio Pizzichini
  url: https://weswrites.me/
  email: valerio.pizzichini@pm.me

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: true
    site_fqdn: 'weswrites.me'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 
  'README.md', 
  'COPYING',
  'Gemfile',
  'Gemfile.lock',
  'LICENSE.md',
  'vendor'
]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

